# PyTorch

In [2]:
import torch

torch.__version__

'2.10.0+cpu'

# Tensor Types

In [5]:
torch.Tensor([1, 2, 3]) # As List -> float by default 
torch.Tensor((1, 2, 3)) # As Tuple -> float by default


import numpy as np
tensor_1 = torch.from_numpy(np.array([1, 2, 3])) # From Numpy Array
tensor_1.dtype

torch.int64

In [7]:
torch.FloatTensor((1, 2, 3))

tensor([1., 2., 3.])

In [8]:
torch.DoubleTensor((1, 2, 3))

tensor([1., 2., 3.], dtype=torch.float64)

In [9]:
torch.ShortTensor((1, 2, 3))

tensor([1, 2, 3], dtype=torch.int16)

In [12]:
torch.BoolTensor((1, 0, 3))

tensor([ True, False,  True])

In [17]:
y = torch.view_as_complex(torch.Tensor([1, 2]))

In [18]:
y.dtype

torch.complex64

# Tensor Operations

In [20]:
tensor_a = torch.Tensor([1, 2, 3])
tensor_b = torch.Tensor([4, 5, 6])

# Addition
result = tensor_a + tensor_b
print(result)
# Subtraction
result2 = tensor_a - tensor_b
print(result2)
# Element-wise Multiplication
result3 = tensor_a * tensor_b
print(result3)

tensor([5., 7., 9.])
tensor([-3., -3., -3.])
tensor([ 4., 10., 18.])


In [22]:
# Element-wise Division
result4 = tensor_a / tensor_b
print(result4)

tensor([0.2500, 0.4000, 0.5000])


In [25]:
# Matrix Multiplication
result5 = torch.matmul(tensor_a, tensor_b)
print(result5)


# Matrix Multiplication single list vs list of list
tensor_d = torch.Tensor([1,2])
tensor_c = torch.Tensor([[1, 2, 3], [4, 5, 6]])
result6 = torch.matmul(tensor_d, tensor_c)
print(result6)  

tensor(32.)
tensor([ 9., 12., 15.])


# Gradients and AutoGrad

In [34]:
x = torch.Tensor([2.0])
x.requires_grad = True # Enable gradient tracking for x

In [35]:
y = x ** 3
y

tensor([8.], grad_fn=<PowBackward0>)

In [36]:
y.backward() # Compute the gradients (derivative of y with respect to x)

In [37]:
x

tensor([2.], requires_grad=True)

In [38]:
x.grad

tensor([12.])

f(x) = x ** 3
df(x) / d(x) = 3 x ** 2 = 3(2)**2 = 12

# Neural Network With PyTorch

In [40]:
inputs = torch.Tensor([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]])
targets = torch.Tensor([[0.0], [1.0], [1.0], [0.0]])

In [41]:
inputs

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])

In [42]:
targets

tensor([[0.],
        [1.],
        [1.],
        [0.]])

In [43]:
import torch.nn as nn 
import torch.optim as optim #optimizers

In [44]:
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.fc1 = nn.Linear(in_features=2, out_features=2) # Fully connected layer with 2 inputs and 2 outputs
        self.fc2 = nn.Linear(2, 1) # Linear layer with 2 inputs and 1 output

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        return self.fc2(x)

In [ ]:
model = Model()

# Print model parameters
for param in model.parameters():
    print(param)


# Define loss function and optimizer
loss_function = nn.MSELoss() # Mean Squared Error Loss
optimizer = optim.Adam(model.parameters(), lr=0.01) # Adam optimizer with learning rate of 0.01

Parameter containing:
tensor([[-0.3480,  0.4672],
        [ 0.3645, -0.0505]], requires_grad=True)
Parameter containing:
tensor([-0.0986, -0.6618], requires_grad=True)
Parameter containing:
tensor([[-0.5380, -0.0360]], requires_grad=True)
Parameter containing:
tensor([-0.1937], requires_grad=True)


In [47]:
for epoch in range(200):
    predictions = model(inputs) # Forward pass: compute predicted outputs by passing inputs to the model
    loss = loss_function(predictions, targets) # Calculate the loss
    loss.backward() # Backward pass: compute gradient of the loss with respect to model parameters
    optimizer.step() # Update model parameters using the optimizer
    optimizer.zero_grad() # Clear the gradients for the next iteration

    if(epoch + 1) % 10 == 0: # Print loss every 10 epochs
        print(f'Epoch [{epoch+1}/200], Loss: {loss.item():.4f}')

Epoch [10/200], Loss: 0.6790
Epoch [20/200], Loss: 0.5317
Epoch [30/200], Loss: 0.4413
Epoch [40/200], Loss: 0.3791
Epoch [50/200], Loss: 0.3335
Epoch [60/200], Loss: 0.3015
Epoch [70/200], Loss: 0.2803
Epoch [80/200], Loss: 0.2669
Epoch [90/200], Loss: 0.2589
Epoch [100/200], Loss: 0.2544
Epoch [110/200], Loss: 0.2520
Epoch [120/200], Loss: 0.2509
Epoch [130/200], Loss: 0.2503
Epoch [140/200], Loss: 0.2501
Epoch [150/200], Loss: 0.2500
Epoch [160/200], Loss: 0.2500
Epoch [170/200], Loss: 0.2500
Epoch [180/200], Loss: 0.2500
Epoch [190/200], Loss: 0.2500
Epoch [200/200], Loss: 0.2500
